### ISSUE TITLE
Translation to English

### ISSUE THREAD

**Issue by egor-bogomolov** [sonoisa/code2vec#1]
Hello, @sonoisa ! I was excited when I saw that your implementation of code2vec is based on PyTorch and even planned to use it in my research. However, all comments as well as commit messages are in Japanese which makes understanding of the implementation and extending it way harder. Do you have any plans on translating them? I'm sure that community would find it useful to have a good pytorch-based code2vec but in this case language barrier can become a problem :)

**Comment by sonoisa** [comment]
Hi, @egor-bogomolov . I just translated the comments to English. In addition, I added a large data set; top11_dataset.

**Comment by egor-bogomolov** [comment]
Thanks a lot!
